<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260808144033 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE employee (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, did VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, fullname VARCHAR(255) NOT NULL, role VARCHAR(10) NOT NULL, nip VARCHAR(32) NOT NULL, entry_year SMALLINT NOT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, token_hash VARCHAR(64) DEFAULT NULL, token_status VARCHAR(10) DEFAULT NULL, token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, unit_id BIGINT NOT NULL, PRIMARY KEY (id), CONSTRAINT CHECK_role CHECK (role IN (\'dosen\', \'staff\')), CONSTRAINT CHECK_status_employee CHECK (status IN (\'active\', \'resigned\', \'suspended\')))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D9F75A14E7FCF41 ON employee (did)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D9F75A1E7927C74 ON employee (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D9F75A159329EEA ON employee (nip)');
        $this->addSql('CREATE INDEX IDX_5D9F75A1F8BD700D ON employee (unit_id)');
        $this->addSql('CREATE TABLE org_unit (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(20) NOT NULL, name VARCHAR(255) NOT NULL, parent_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_455318CB77153098 ON org_unit (code)');
        $this->addSql('CREATE INDEX IDX_455318CB727ACA70 ON org_unit (parent_id)');
        $this->addSql('CREATE TABLE student (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, did VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, fullname VARCHAR(255) NOT NULL, nim VARCHAR(32) NOT NULL, entry_year SMALLINT NOT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, token_hash VARCHAR(64) DEFAULT NULL, token_status VARCHAR(10) DEFAULT NULL, token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, unit_id BIGINT NOT NULL, PRIMARY KEY (id), CONSTRAINT CHECK_status_student CHECK (status IN (\'active\', \'graduated\', \'suspended\')))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B723AF334E7FCF41 ON student (did)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B723AF33E7927C74 ON student (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B723AF333A34F233 ON student (nim)');
        $this->addSql('CREATE INDEX IDX_B723AF33F8BD700D ON student (unit_id)');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1F8BD700D FOREIGN KEY (unit_id) REFERENCES org_unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE org_unit ADD CONSTRAINT FK_455318CB727ACA70 FOREIGN KEY (parent_id) REFERENCES org_unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33F8BD700D FOREIGN KEY (unit_id) REFERENCES org_unit (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE employee DROP CONSTRAINT FK_5D9F75A1F8BD700D');
        $this->addSql('ALTER TABLE org_unit DROP CONSTRAINT FK_455318CB727ACA70');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33F8BD700D');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE org_unit');
        $this->addSql('DROP TABLE student');
    }
}
