<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260827120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create cnonce table for OID4VCI nonce endpoint.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cnonce (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CNONCE_VALUE ON cnonce (value)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cnonce');
    }
}
